version: "3.9"
services:
  api:
    image: matthewreinert/personal-finance-api
    container_name: api
    build:
      context: ./api
    environment:
      - SERVER_PORT=80
    ports:
      - "9000:80"
  spa:
    image: matthewreinert/personal-finance-spa
    container_name: spa
    build:
      context: ./spa
    ports:
      - "4200:80"
    depends_on:
      - api  